wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.0rc1
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1715962755.0
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 45
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 45
      - 55
      3:
      - 13
      - 23
      - 61
      4: 3.11.0rc1
      5: 0.16.6
      8:
      - 5
      13: linux-x86_64
